version: '2'

services:
  relayer:
    build: ./
    restart: always
    environment:
      NODE_ENV: production
      VIRTUAL_HOST: relayer.tornado.cash
      LETSENCRYPT_HOST: relayer.tornado.cash
    env_file: ./.env